### ISSUE TITLE
Application does not start on Android 4.3

### ISSUE THREAD

**Issue by algernon** [eggplantPrince/tootyFruity#1]
I'm trying to start the application on a Samsung Galaxy S3 (Android 4.3, I believe), installed from the Google Play Sore. On first start, an error dialog greeted me, saying `"The connection to the server was unsuccessful. (file:///android_asset/www/index.html)"`.

The phone is not jailbroken.

**Comment by eggplantPrince** [comment]
Ionic 2 appa requiere at least 4.4 to run. The next version will have this as a min requirement to even be able to download.
